### ISSUE TITLE
mainline?

### ISSUE THREAD

**Issue by ghost** [qzed/linux-surfacegen5-button-driver#1]
what work needs to be done to get this module / patch merged into mainline?
it would be really nice to get the buttons working with a mainline kernel

**Comment by qzed** [comment]
I agree, at some point this should end up in mainline. I tried to keep it as close as possible to the original ([soc_button_array.c](https://github.com/torvalds/linux/blob/864af0d40cdc82b705e3ca79cf2a57be900954b1/drivers/input/misc/soc_button_array.c)) so it should not be too hard to write a patch for it. The only catch is that this clashes with the mainline `surfacepro3_button` module, so [this](https://github.com/jakeday/linux-surface/blob/master/patches/4.17/buttons.patch#L277-L299) also needs to be included in the patch.

Unfortunately, I don't have any experience with the whole kernel development process, e.g. where to submit a patch etc. Furthermore, I don't have much time at the moment, I'll look into this once I do.

Also there is one remaining issue that I want to tackle before that: I want to make sure that the volume keys on the device are distinguishable from the keys on the keyboard, so that they could be remapped independently in user-space, e.g. with a script that reverses the on-device buttons depending on the orientation of the device. (I think this should already work, I just want to make sure it works not only on my device before submitting a patch).

**Comment by qzed** [comment]
Possible issues blocking this:
- <s>https://github.com/jakeday/linux-surface/issues/224</s>
- <s>https://github.com/jakeday/linux-surface/issues/243</s>
- <s>https://github.com/jakeday/linux-surface/issues/401</s>

**Comment by qzed** [comment]
Patch has been sent upstream (https://www.spinics.net/lists/linux-input/msg62051.html), waiting for a response.

**Comment by qzed** [comment]
On its way into v5.4: https://git.kernel.org/pub/scm/linux/kernel/git/dtor/input.git/commit/?h=next&id=c394159310d02defcfe63c617f13b0c2974725c5.
